export const NotFound_Code = 404;
export const NotFound = 'File Not Found...';
export const Created = 201;
export const Ok_Code = 200;
export const Ok = "Successful...";
export const Forbidden = 403;
export const Unauthorized = 401;
export const InternalServer_Code = 500;
export const InternalServer = "Something Went Wrong..."
export const Exists_Code = 400;
export const Exists = "User Already Exists...";